using MediCamp.Models;
using MediCamp.Models.Domain;
using Microsoft.EntityFrameworkCore;

namespace MediCamp.Data
{
    public static class DbSeeder
    {
        public static void SeedData(ApplicationDbContext dbContext)
        {
            // 0. Ensure Phase 7 tables exist
            try
            {
                dbContext.Database.ExecuteSqlRaw(@"
                    ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""PatientUniqueId"" character varying(10);
                    ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""DoctorApprovalStatus"" character varying(20) DEFAULT 'Approved';
                    ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""DoctorRejectionReason"" text;

                    CREATE TABLE IF NOT EXISTS ""BloodRequests"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""RequesterId"" text NOT NULL,
                        ""BloodGroup"" character varying(10) NOT NULL,
                        ""UnitsRequired"" integer NOT NULL DEFAULT 1,
                        ""Urgency"" character varying(20) NOT NULL DEFAULT 'Urgent',
                        ""HospitalName"" character varying(150) NOT NULL DEFAULT '',
                        ""District"" character varying(50) NOT NULL DEFAULT '',
                        ""Upazila"" character varying(50) NOT NULL DEFAULT '',
                        ""ContactNumber"" character varying(20) NOT NULL DEFAULT '',
                        ""Reason"" character varying(500),
                        ""Status"" character varying(30) NOT NULL DEFAULT 'Open',
                        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        ""NeededByDate"" timestamp with time zone,
                        CONSTRAINT ""FK_BloodRequests_Users_RequesterId"" FOREIGN KEY (""RequesterId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                    );

                    CREATE TABLE IF NOT EXISTS ""BloodDonationLogs"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""DonorId"" text NOT NULL,
                        ""DonatedDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        ""VenueOrHospital"" character varying(150) NOT NULL DEFAULT '',
                        ""BloodRequestId"" integer,
                        ""Notes"" character varying(500),
                        CONSTRAINT ""FK_BloodDonationLogs_Users_DonorId"" FOREIGN KEY (""DonorId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE,
                        CONSTRAINT ""FK_BloodDonationLogs_BloodRequests_BloodRequestId"" FOREIGN KEY (""BloodRequestId"") REFERENCES ""BloodRequests"" (""Id"") ON DELETE SET NULL
                    );

                    CREATE TABLE IF NOT EXISTS ""CampPatientRegistrations"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""CampId"" integer NOT NULL,
                        ""PatientId"" text NOT NULL,
                        ""Status"" character varying(30) NOT NULL DEFAULT 'Registered',
                        ""RegisteredAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT ""FK_CampPatientRegistrations_Camps_CampId"" FOREIGN KEY (""CampId"") REFERENCES ""Camps"" (""Id"") ON DELETE CASCADE,
                        CONSTRAINT ""FK_CampPatientRegistrations_Users_PatientId"" FOREIGN KEY (""PatientId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                    );

                    CREATE TABLE IF NOT EXISTS ""CampExpenses"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""CampId"" integer NOT NULL,
                        ""Category"" character varying(100) NOT NULL DEFAULT 'Medicines & Medical Supplies',
                        ""Amount"" numeric(18,2) NOT NULL DEFAULT 0,
                        ""Description"" character varying(500),
                        ""ExpenseDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        ""LoggedByUserId"" text,
                        CONSTRAINT ""FK_CampExpenses_Camps_CampId"" FOREIGN KEY (""CampId"") REFERENCES ""Camps"" (""Id"") ON DELETE CASCADE,
                        CONSTRAINT ""FK_CampExpenses_Users_LoggedByUserId"" FOREIGN KEY (""LoggedByUserId"") REFERENCES ""Users"" (""Id"") ON DELETE SET NULL
                    );
                ");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Table creation info: {ex.Message}");
            }

            // 1. Seed Users (Upsert to guarantee all demo credentials always work)
            var users = new List<ApplicationUser>
            {
                new ApplicationUser
                {
                    Id = "usr-admin-01",
                    FullName = "Prof. Dr. Tanvir Hasan",
                    Email = "admin@medicamp.org",
                    PhoneNumber = "01711000001",
                    NID = "19782690011223344",
                    Role = SystemRoles.Admin,
                    District = "Dhaka",
                    Upazila = "Dhanmondi",
                    Address = "MediCamp Central HQ, Level 4, Dhanmondi 27, Dhaka",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow.AddMonths(-6),
                    LastLoginAt = DateTime.UtcNow.AddHours(-1),
                    PasswordHash = "Admin@123"
                },
                new ApplicationUser
                {
                    Id = "usr-host-01",
                    FullName = "Shahidul Alam",
                    Email = "host@brachospital.org",
                    PhoneNumber = "01819000002",
                    NID = "19822690022334455",
                    Role = SystemRoles.Host,
                    District = "Dhaka",
                    Upazila = "Mohakhali",
                    Address = "BRAC Centre, 75 Mohakhali, Dhaka-1212",
                    OrganizationName = "BRAC Community Health Initiative",
                    OrganizationRegNo = "NGOAB-2018-0492",
                    FocalPersonContact = "01819000002",
                    HostApprovalStatus = "Approved",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow.AddMonths(-4),
                    LastLoginAt = DateTime.UtcNow.AddHours(-3),
                    PasswordHash = "Host@123"
                },
                new ApplicationUser
                {
                    Id = "usr-host-02",
                    FullName = "Dr. Shamsul Huda",
                    Email = "host.green@gmail.com",
                    PhoneNumber = "01912000003",
                    NID = "19862690033445566",
                    Role = SystemRoles.Host,
                    District = "Sylhet",
                    Upazila = "Kotwali",
                    Address = "Green Crescent Foundation, Zindabazar, Sylhet",
                    OrganizationName = "Green Crescent Humanitarian Aid",
                    OrganizationType = "NGO",
                    OrganizationRegNo = "NGOAB-2024-1180",
                    FocalPersonContact = "01912000003",
                    HostApprovalStatus = "Pending",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow.AddDays(-2),
                    PasswordHash = "Host@123"
                },
                new ApplicationUser
                {
                    Id = "usr-host-03",
                    FullName = "Mahmudur Rahman",
                    Email = "contact@carebd.org",
                    PhoneNumber = "01711000099",
                    NID = "19852690099887766",
                    Role = SystemRoles.Host,
                    District = "Chittagong",
                    Upazila = "Agrabad",
                    Address = "Agrabad Commercial Area, Chittagong",
                    OrganizationName = "Care BD Relief Trust",
                    OrganizationType = "Community Group",
                    OrganizationRegNo = "COMM-2023-88",
                    FocalPersonContact = "01711000099",
                    HostApprovalStatus = "Rejected",
                    HostRejectionReason = "Organization registration documents could not be verified.",
                    IsActive = false,
                    CreatedAt = DateTime.UtcNow.AddDays(-10),
                    PasswordHash = "Host@123"
                },
                new ApplicationUser
                {
                    Id = "usr-doc-01",
                    FullName = "Dr. Rafiqul Rahman",
                    Email = "doctor.rahman@medicamp.org",
                    PhoneNumber = "01722000004",
                    NID = "19882690044556677",
                    Role = SystemRoles.Doctor,
                    District = "Dhaka",
                    Upazila = "Shahbagh",
                    Address = "BSMMU Doctors Quarter, Shahbagh, Dhaka",
                    MedicalSpecialization = "MBBS, FCPS (Internal Medicine)",
                    BMDCRegNo = "BMDC-A-48291",
                    BloodGroup = "B+",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow.AddMonths(-3),
                    LastLoginAt = DateTime.UtcNow.AddHours(-5),
                    PasswordHash = "Doctor@123"
                },
                new ApplicationUser
                {
                    Id = "usr-doc-02",
                    FullName = "Dr. Fatima Tuz Zohra",
                    Email = "doctor.fatima@medicamp.org",
                    PhoneNumber = "01733000005",
                    NID = "19902690055667788",
                    Role = SystemRoles.Doctor,
                    District = "Chittagong",
                    Upazila = "Panchlaish",
                    Address = "Chittagong Medical College Hospital Area",
                    MedicalSpecialization = "MBBS, DGO (Obstetrics & Gynecology)",
                    BMDCRegNo = "BMDC-A-59124",
                    DoctorApprovalStatus = "Approved",
                    BloodGroup = "O+",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow.AddMonths(-2),
                    PasswordHash = "Doctor@123"
                },
                new ApplicationUser
                {
                    Id = "usr-doc-03",
                    FullName = "Dr. Kazi Anisur Rahman",
                    Email = "doctor.kazi@medicamp.org",
                    PhoneNumber = "01744000007",
                    NID = "19872690077889900",
                    Role = SystemRoles.Doctor,
                    District = "Sylhet",
                    Upazila = "Amberkhana",
                    Address = "Amberkhana Point, Sylhet",
                    MedicalSpecialization = "MBBS, FCPS (Pediatrics)",
                    BMDCRegNo = "BMDC-A-67123",
                    DoctorApprovalStatus = "Pending",
                    BloodGroup = "A+",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow.AddDays(-1),
                    PasswordHash = "Doctor@123"
                },
                new ApplicationUser
                {
                    Id = "usr-doc-04",
                    FullName = "Dr. Mehedi Hasan",
                    Email = "doctor.mehedi@medicamp.org",
                    PhoneNumber = "01755000008",
                    NID = "19842690088990011",
                    Role = SystemRoles.Doctor,
                    District = "Rajshahi",
                    Upazila = "Boalia",
                    Address = "Shaheb Bazar, Rajshahi",
                    MedicalSpecialization = "MBBS (General Practitioner)",
                    BMDCRegNo = "BMDC-A-99999",
                    DoctorApprovalStatus = "Rejected",
                    DoctorRejectionReason = "BMDC registration credentials could not be verified in the national medical council registry.",
                    BloodGroup = "B+",
                    IsActive = false,
                    CreatedAt = DateTime.UtcNow.AddDays(-5),
                    PasswordHash = "Doctor@123"
                },
                new ApplicationUser
                {
                    Id = "usr-vol-01",
                    FullName = "Karim Ahmed",
                    Email = "volunteer.karim@medicamp.org",
                    PhoneNumber = "01511000006",
                    NID = "19962690066778899",
                    Role = SystemRoles.Volunteer,
                    District = "Kurigram",
                    Upazila = "Chilmari",
                    Address = "Char Chilmari, Ward 3, Kurigram",
                    BloodGroup = "A+",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow.AddMonths(-2),
                    LastLoginAt = DateTime.UtcNow.AddHours(-2),
                    PasswordHash = "Volunteer@123"
                },
                new ApplicationUser
                {
                    Id = "usr-vol-02",
                    FullName = "Sadia Sultana",
                    Email = "volunteer.sadia@medicamp.org",
                    PhoneNumber = "01611000007",
                    NID = "19982690077889900",
                    Role = SystemRoles.Volunteer,
                    District = "Sunamganj",
                    Upazila = "Tahirpur",
                    Address = "Tahirpur Bazar, Sunamganj",
                    BloodGroup = "AB+",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow.AddDays(-20),
                    PasswordHash = "Volunteer@123"
                },
                new ApplicationUser
                {
                    Id = "usr-pharma-01",
                    FullName = "Nusrat Poly",
                    Email = "pharma.poly@medicamp.org",
                    PhoneNumber = "01755000008",
                    NID = "19942690088990011",
                    Role = SystemRoles.Pharmacist,
                    District = "Rangpur",
                    Upazila = "Kotwali",
                    Address = "Dhap Medical Road, Rangpur",
                    BloodGroup = "O-",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow.AddMonths(-2),
                    LastLoginAt = DateTime.UtcNow.AddDays(-1),
                    PasswordHash = "Pharma@123"
                },
                new ApplicationUser
                {
                    Id = "usr-pat-01",
                    FullName = "Anwar Hossain",
                    Email = "patient.anwar@medicamp.org",
                    PhoneNumber = "01822000009",
                    NID = "19852691234567890",
                    Role = SystemRoles.Patient,
                    District = "Kurigram",
                    Upazila = "Chilmari",
                    Address = "South Ramna Village, Chilmari, Kurigram",
                    BloodGroup = "B+",
                    DateOfBirth = new DateTime(1985, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                    Gender = "Male",
                    PatientUniqueId = "A3K9P2",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow.AddMonths(-1),
                    PasswordHash = "Patient@123"
                },
                new ApplicationUser
                {
                    Id = "usr-pat-02",
                    FullName = "Mariam Begum",
                    Email = "patient.mariam@medicamp.org",
                    PhoneNumber = "01933000010",
                    NID = "19922695432109876",
                    Role = SystemRoles.Patient,
                    District = "Sunamganj",
                    Upazila = "Tahirpur",
                    Address = "Bishwamvarpur Road, Sunamganj",
                    BloodGroup = "A+",
                    DateOfBirth = new DateTime(1992, 9, 25, 0, 0, 0, DateTimeKind.Utc),
                    Gender = "Female",
                    PatientUniqueId = "MX04TR",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow.AddDays(-15),
                    PasswordHash = "Patient@123"
                }
            };

            foreach (var u in users)
            {
                var existing = dbContext.Users.FirstOrDefault(x => x.Id == u.Id || x.Email.ToLower() == u.Email.ToLower());
                if (existing == null)
                {
                    dbContext.Users.Add(u);
                }
                else
                {
                    // Update credentials to ensure demo login always works without resetting admin approval state
                    existing.PasswordHash = u.PasswordHash;

                    if (string.IsNullOrEmpty(existing.HostApprovalStatus) && u.Role == SystemRoles.Host)
                    {
                        existing.HostApprovalStatus = u.HostApprovalStatus;
                    }
                    if (string.IsNullOrEmpty(existing.PatientUniqueId) && !string.IsNullOrEmpty(u.PatientUniqueId))
                    {
                        existing.PatientUniqueId = u.PatientUniqueId;
                    }
                    if (u.Role == SystemRoles.Doctor && string.IsNullOrEmpty(existing.BMDCRegNo))
                    {
                        existing.MedicalSpecialization = u.MedicalSpecialization;
                        existing.BMDCRegNo = u.BMDCRegNo;
                    }
                }
            }
            dbContext.SaveChanges();

            // Backfill any patients in database that lack a PatientUniqueId
            var missingPatientIds = dbContext.Users.Where(u => u.Role == SystemRoles.Patient && string.IsNullOrEmpty(u.PatientUniqueId)).ToList();
            foreach (var p in missingPatientIds)
            {
                p.PatientUniqueId = Services.MockDataService.GenerateUniquePatientId(dbContext);
            }
            if (missingPatientIds.Any())
            {
                dbContext.SaveChanges();
            }

            // 2. Seed Camps
            if (!dbContext.Camps.Any())
            {
                var camps = new List<Camp>
                {
                    new Camp
                    {
                        Title = "Kurigram Chilmari Char Free Healthcare & Screening Camp",
                        CampType = "General Healthcare & Triage",
                        District = "Kurigram",
                        Upazila = "Chilmari",
                        Venue = "Chilmari High School Ground",
                        StartDate = DateTime.UtcNow.AddDays(3),
                        EndDate = DateTime.UtcNow.AddDays(5),
                        ExpectedPatients = 1200,
                        RegisteredPatientsCount = 0,
                        ServedPatientsCount = 0,
                        TotalBudget = 150000.00m,
                        UtilizedBudget = 45000.00m,
                        Status = "Scheduled",
                        HostId = "usr-host-01",
                        Description = "Free medical care and essential diagnostic screening for flood-affected char communities."
                    },
                    new Camp
                    {
                        Title = "Sunamganj Haor Remote Maternal & Child Healthcare Camp",
                        CampType = "Maternal & Child Care",
                        District = "Sunamganj",
                        Upazila = "Tahirpur",
                        Venue = "Tahirpur Union Parishad Health Complex",
                        StartDate = DateTime.UtcNow.AddDays(-1),
                        EndDate = DateTime.UtcNow.AddDays(2),
                        ExpectedPatients = 850,
                        RegisteredPatientsCount = 450,
                        ServedPatientsCount = 412,
                        TotalBudget = 120000.00m,
                        UtilizedBudget = 88000.00m,
                        Status = "Ongoing",
                        HostId = "usr-host-01",
                        Description = "Specialized obstetric, gynecological, and pediatric healthcare services in remote haor areas."
                    },
                    new Camp
                    {
                        Title = "Bandarban Ruma Hill Tracts Community Vision & Dental Camp",
                        CampType = "Eye & Dental Specialist",
                        District = "Bandarban",
                        Upazila = "Ruma",
                        Venue = "Ruma Model Primary School",
                        StartDate = DateTime.UtcNow.AddDays(12),
                        EndDate = DateTime.UtcNow.AddDays(14),
                        ExpectedPatients = 600,
                        RegisteredPatientsCount = 0,
                        ServedPatientsCount = 0,
                        TotalBudget = 95000.00m,
                        UtilizedBudget = 15000.00m,
                        Status = "Scheduled",
                        HostId = "usr-host-02",
                        Description = "Dental procedures, eye examinations, and free distribution of prescription glasses."
                    }
                };

                dbContext.Camps.AddRange(camps);
                dbContext.SaveChanges();
            }

            // 3. Seed Master Medicines
            var masterMedicinesList = new List<MasterMedicine>
            {
                new MasterMedicine { BrandName = "Napa Extra", GenericName = "Paracetamol + Caffeine", DosageForm = "Tablet", Strength = "500mg+65mg", Category = "Analgesic", IsEssential = true },
                new MasterMedicine { BrandName = "Seclo 20", GenericName = "Omeprazole", DosageForm = "Capsule", Strength = "20mg", Category = "Gastric", IsEssential = true },
                new MasterMedicine { BrandName = "Cef-3", GenericName = "Cefixime", DosageForm = "Capsule", Strength = "200mg", Category = "Antibiotic", IsEssential = true },
                new MasterMedicine { BrandName = "Histacin", GenericName = "Chlorpheniramine", DosageForm = "Tablet", Strength = "4mg", Category = "Antihistamine", IsEssential = true },
                new MasterMedicine { BrandName = "Bexidal", GenericName = "Multivitamin", DosageForm = "Syrup", Strength = "100ml", Category = "Vitamin", IsEssential = true },
                new MasterMedicine { BrandName = "Amodis 400", GenericName = "Metronidazole", DosageForm = "Tablet", Strength = "400mg", Category = "Antiprotozoal", IsEssential = true },
                new MasterMedicine { BrandName = "Zimax 500", GenericName = "Azithromycin", DosageForm = "Tablet", Strength = "500mg", Category = "Antibiotic", IsEssential = false },
                new MasterMedicine { BrandName = "Monas 10", GenericName = "Montelukast", DosageForm = "Tablet", Strength = "10mg", Category = "Respiratory", IsEssential = false },
                new MasterMedicine { BrandName = "Camlodin 5", GenericName = "Amlodipine", DosageForm = "Tablet", Strength = "5mg", Category = "Cardiovascular", IsEssential = true },
                new MasterMedicine { BrandName = "Comet 500", GenericName = "Metformin", DosageForm = "Tablet", Strength = "500mg", Category = "Antidiabetic", IsEssential = true },
                new MasterMedicine { BrandName = "ORSaline-N", GenericName = "Oral Rehydration Salt", DosageForm = "Sachet", Strength = "500ml", Category = "Electrolyte", IsEssential = true },
                new MasterMedicine { BrandName = "Ventolin Inhaler", GenericName = "Salbutamol", DosageForm = "Inhaler", Strength = "100mcg/puff", Category = "Respiratory", IsEssential = false }
            };

            foreach (var med in masterMedicinesList)
            {
                if (!dbContext.MasterMedicines.Any(m => m.BrandName.ToLower() == med.BrandName.ToLower()))
                {
                    dbContext.MasterMedicines.Add(med);
                }
            }
            dbContext.SaveChanges();

            // 4. Seed Locations (Divisions, Districts, Upazilas for dynamic lookup)
            if (!dbContext.Locations.Any())
            {
                var locations = new List<Location>
                {
                    // Dhaka Division
                    new Location { Division = "Dhaka", District = "Dhaka", Upazila = "Dhanmondi" },
                    new Location { Division = "Dhaka", District = "Dhaka", Upazila = "Mohakhali" },
                    new Location { Division = "Dhaka", District = "Dhaka", Upazila = "Gulshan" },
                    new Location { Division = "Dhaka", District = "Dhaka", Upazila = "Uttara" },
                    new Location { Division = "Dhaka", District = "Dhaka", Upazila = "Mirpur" },
                    new Location { Division = "Dhaka", District = "Dhaka", Upazila = "Savar" },
                    new Location { Division = "Dhaka", District = "Gazipur", Upazila = "Gazipur Sadar" },
                    new Location { Division = "Dhaka", District = "Gazipur", Upazila = "Sreepur" },
                    new Location { Division = "Dhaka", District = "Gazipur", Upazila = "Kaliakair" },
                    new Location { Division = "Dhaka", District = "Narayanganj", Upazila = "Narayanganj Sadar" },
                    new Location { Division = "Dhaka", District = "Narayanganj", Upazila = "Rupganj" },
                    new Location { Division = "Dhaka", District = "Narayanganj", Upazila = "Sonargaon" },

                    // Rangpur Division
                    new Location { Division = "Rangpur", District = "Kurigram", Upazila = "Chilmari" },
                    new Location { Division = "Rangpur", District = "Kurigram", Upazila = "Nageswari" },
                    new Location { Division = "Rangpur", District = "Kurigram", Upazila = "Bhurungamari" },
                    new Location { Division = "Rangpur", District = "Kurigram", Upazila = "Kurigram Sadar" },
                    new Location { Division = "Rangpur", District = "Kurigram", Upazila = "Ulipur" },
                    new Location { Division = "Rangpur", District = "Rangpur", Upazila = "Kotwali" },
                    new Location { Division = "Rangpur", District = "Rangpur", Upazila = "Mithapukur" },
                    new Location { Division = "Rangpur", District = "Rangpur", Upazila = "Pirganj" },

                    // Sylhet Division
                    new Location { Division = "Sylhet", District = "Sunamganj", Upazila = "Tahirpur" },
                    new Location { Division = "Sylhet", District = "Sunamganj", Upazila = "Bishwamvarpur" },
                    new Location { Division = "Sylhet", District = "Sunamganj", Upazila = "Chhatak" },
                    new Location { Division = "Sylhet", District = "Sunamganj", Upazila = "Sunamganj Sadar" },
                    new Location { Division = "Sylhet", District = "Sylhet", Upazila = "Kotwali" },
                    new Location { Division = "Sylhet", District = "Sylhet", Upazila = "Beanibazar" },
                    new Location { Division = "Sylhet", District = "Sylhet", Upazila = "Gowainghat" },

                    // Chittagong Division
                    new Location { Division = "Chittagong", District = "Bandarban", Upazila = "Ruma" },
                    new Location { Division = "Chittagong", District = "Bandarban", Upazila = "Thanchi" },
                    new Location { Division = "Chittagong", District = "Bandarban", Upazila = "Lama" },
                    new Location { Division = "Chittagong", District = "Bandarban", Upazila = "Bandarban Sadar" },
                    new Location { Division = "Chittagong", District = "Chittagong", Upazila = "Panchlaish" },
                    new Location { Division = "Chittagong", District = "Chittagong", Upazila = "Agrabad" },
                    new Location { Division = "Chittagong", District = "Chittagong", Upazila = "Hathazari" },
                    new Location { Division = "Chittagong", District = "Chittagong", Upazila = "Sitakunda" },

                    // Khulna Division
                    new Location { Division = "Khulna", District = "Khulna", Upazila = "Khulna Sadar" },
                    new Location { Division = "Khulna", District = "Khulna", Upazila = "Rupsha" },
                    new Location { Division = "Khulna", District = "Khulna", Upazila = "Batiaghata" },

                    // Barisal Division
                    new Location { Division = "Barisal", District = "Barisal", Upazila = "Barisal Sadar" },
                    new Location { Division = "Barisal", District = "Barisal", Upazila = "Bakerganj" },

                    // Rajshahi Division
                    new Location { Division = "Rajshahi", District = "Rajshahi", Upazila = "Boalia" },
                    new Location { Division = "Rajshahi", District = "Rajshahi", Upazila = "Paba" },

                    // Mymensingh Division
                    new Location { Division = "Mymensingh", District = "Mymensingh", Upazila = "Mymensingh Sadar" },
                    new Location { Division = "Mymensingh", District = "Mymensingh", Upazila = "Muktagacha" }
                };

                dbContext.Locations.AddRange(locations);
                dbContext.SaveChanges();
            }

            // 5. Seed Blood Donation Profiles
            if (!dbContext.BloodDonationProfiles.Any())
            {
                var patients = dbContext.Users.Where(u => u.Role == SystemRoles.Patient || u.Role == SystemRoles.Volunteer).ToList();
                var profiles = new List<BloodDonationProfile>();

                foreach (var p in patients)
                {
                    profiles.Add(new BloodDonationProfile
                    {
                        UserId              = p.Id,
                        BloodGroup          = p.BloodGroup ?? "O+",
                        District            = p.District ?? "Dhaka",
                        Upazila             = p.Upazila ?? "Dhanmondi",
                        IsAvailableDonor    = true,
                        TotalDonationsCount = 2,
                        LastDonatedDate     = DateTime.UtcNow.AddMonths(-4),
                        WeightKg            = 68.0
                    });
                }

                dbContext.BloodDonationProfiles.AddRange(profiles);
                dbContext.SaveChanges();
            }

            // 6. Seed Sample Blood Requests
            if (!dbContext.BloodRequests.Any())
            {
                var requester = dbContext.Users.FirstOrDefault(u => u.Role == SystemRoles.Patient);
                if (requester != null)
                {
                    var requests = new List<BloodRequest>
                    {
                        new BloodRequest
                        {
                            RequesterId   = requester.Id,
                            BloodGroup    = "O+",
                            UnitsRequired = 2,
                            Urgency       = "Critical",
                            HospitalName  = "Dhaka Medical College Hospital (ICU Ward 3)",
                            District      = "Dhaka",
                            Upazila       = "Dhanmondi",
                            ContactNumber = requester.PhoneNumber,
                            Reason        = "Emergency transfusion for post-operative patient with severe anemia.",
                            Status        = "Open",
                            CreatedAt     = DateTime.UtcNow.AddHours(-2)
                        },
                        new BloodRequest
                        {
                            RequesterId   = requester.Id,
                            BloodGroup    = "B+",
                            UnitsRequired = 1,
                            Urgency       = "Urgent",
                            HospitalName  = "Kurigram Sadar Hospital",
                            District      = "Kurigram",
                            Upazila       = "Kurigram Sadar",
                            ContactNumber = requester.PhoneNumber,
                            Reason        = "Thalassemia patient monthly routine transfusion.",
                            Status        = "Open",
                            CreatedAt     = DateTime.UtcNow.AddHours(-6)
                        }
                    };

                    dbContext.BloodRequests.AddRange(requests);
                    dbContext.SaveChanges();
                }
            }

            // 7. Seed Additional Diverse Patients (if few exist)
            if (dbContext.Users.Count(u => u.Role == SystemRoles.Patient) < 6)
            {
                var extraPatients = new List<ApplicationUser>
                {
                    new ApplicationUser
                    {
                        Id = "usr-pat-03",
                        FullName = "Rashidul Huq",
                        Email = "patient.rashid@medicamp.org",
                        PhoneNumber = "01788112233",
                        NID = "19752690011223301",
                        Role = SystemRoles.Patient,
                        District = "Kurigram",
                        Upazila = "Chilmari",
                        Address = "Vatirdangi, Chilmari, Kurigram",
                        BloodGroup = "O+",
                        DateOfBirth = new DateTime(1962, 3, 10, 0, 0, 0, DateTimeKind.Utc), // Geriatric 60+
                        Gender = "Male",
                        PatientUniqueId = "C7R2K9",
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow.AddMonths(-3),
                        PasswordHash = "Patient@123"
                    },
                    new ApplicationUser
                    {
                        Id = "usr-pat-04",
                        FullName = "Sumaiya Akter",
                        Email = "patient.sumaiya@medicamp.org",
                        PhoneNumber = "01899223344",
                        NID = "20052690011223302",
                        Role = SystemRoles.Patient,
                        District = "Sunamganj",
                        Upazila = "Tahirpur",
                        Address = "Matikata Village, Tahirpur",
                        BloodGroup = "AB+",
                        DateOfBirth = new DateTime(2005, 8, 15, 0, 0, 0, DateTimeKind.Utc), // Youth 15-24
                        Gender = "Female",
                        PatientUniqueId = "S9B4X1",
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow.AddMonths(-2),
                        PasswordHash = "Patient@123"
                    },
                    new ApplicationUser
                    {
                        Id = "usr-pat-05",
                        FullName = "Tanvir Rahman (Child)",
                        Email = "patient.child.tanvir@medicamp.org",
                        PhoneNumber = "01944332211",
                        Role = SystemRoles.Patient,
                        District = "Bandarban",
                        Upazila = "Ruma",
                        Address = "Boga Lake Road, Ruma",
                        BloodGroup = "A-",
                        DateOfBirth = new DateTime(2018, 6, 20, 0, 0, 0, DateTimeKind.Utc), // Pediatric <15
                        Gender = "Male",
                        PatientUniqueId = "T2M8V5",
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow.AddMonths(-1),
                        PasswordHash = "Patient@123"
                    },
                    new ApplicationUser
                    {
                        Id = "usr-pat-06",
                        FullName = "Rabeya Khatun",
                        Email = "patient.rabeya@medicamp.org",
                        PhoneNumber = "01677889900",
                        NID = "19602690011223304",
                        Role = SystemRoles.Patient,
                        District = "Dhaka",
                        Upazila = "Mohakhali",
                        Address = "Korail Bastee, Mohakhali, Dhaka",
                        BloodGroup = "B-",
                        DateOfBirth = new DateTime(1958, 11, 5, 0, 0, 0, DateTimeKind.Utc), // Geriatric 60+
                        Gender = "Female",
                        PatientUniqueId = "R6W1L8",
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow.AddMonths(-2),
                        PasswordHash = "Patient@123"
                    }
                };

                dbContext.Users.AddRange(extraPatients);
                dbContext.SaveChanges();
            }

            // Also ensure any existing ongoing camps have dates encompassing today
            var ongoingCamps = dbContext.Camps.Where(c => c.Status == "Ongoing").ToList();
            foreach (var oc in ongoingCamps)
            {
                if (oc.StartDate > DateTime.UtcNow || oc.EndDate < DateTime.UtcNow)
                {
                    oc.StartDate = DateTime.UtcNow.AddDays(-2);
                    oc.EndDate = DateTime.UtcNow.AddDays(3);
                }
            }
            if (ongoingCamps.Any())
            {
                dbContext.SaveChanges();
            }

            // 8. Seed Camp Inventories
            if (!dbContext.CampInventories.Any())
            {
                var camps = dbContext.Camps.ToList();
                var medicines = dbContext.MasterMedicines.ToList();

                if (camps.Any() && medicines.Any())
                {
                    var inventories = new List<CampInventory>();
                    foreach (var c in camps)
                    {
                        foreach (var m in medicines)
                        {
                            int allocated = m.Category switch
                            {
                                "Analgesic" => 800,
                                "Gastric" => 600,
                                "Antibiotic" => 350,
                                "Antihistamine" => 400,
                                _ => 250
                            };
                            int dispensed = c.Status == "Ongoing" || c.Status == "Completed" ? (int)(allocated * 0.65) : 0;

                            inventories.Add(new CampInventory
                            {
                                CampId = c.Id,
                                MasterMedicineId = m.Id,
                                QuantityAllocated = allocated,
                                QuantityDispensed = dispensed
                            });
                        }
                    }
                    dbContext.CampInventories.AddRange(inventories);
                    dbContext.SaveChanges();
                }
            }

            // 9. Seed Camp Categorized Expenses
            if (!dbContext.CampExpenses.Any())
            {
                var camp1 = dbContext.Camps.FirstOrDefault(c => c.District == "Kurigram");
                var camp2 = dbContext.Camps.FirstOrDefault(c => c.District == "Sunamganj");
                var hostUser = dbContext.Users.FirstOrDefault(u => u.Role == SystemRoles.Host);

                var expenses = new List<CampExpense>();

                if (camp1 != null)
                {
                    expenses.Add(new CampExpense
                    {
                        CampId = camp1.Id,
                        Category = "Medicines & Medical Supplies",
                        Amount = 22000.00m,
                        Description = "Procurement of essential analgesics, antibiotics, oral saline and dressing materials.",
                        ExpenseDate = DateTime.UtcNow.AddDays(-2),
                        LoggedByUserId = hostUser?.Id
                    });
                    expenses.Add(new CampExpense
                    {
                        CampId = camp1.Id,
                        Category = "Doctor & Staff Honorarium",
                        Amount = 12000.00m,
                        Description = "Travel stipend and daily allowance for 2 volunteer clinicians.",
                        ExpenseDate = DateTime.UtcNow.AddDays(-2),
                        LoggedByUserId = hostUser?.Id
                    });
                    expenses.Add(new CampExpense
                    {
                        CampId = camp1.Id,
                        Category = "Logistics & Transportation",
                        Amount = 6500.00m,
                        Description = "Trawler boat hire across Brahmaputra river to transport field medical team to Char.",
                        ExpenseDate = DateTime.UtcNow.AddDays(-1),
                        LoggedByUserId = hostUser?.Id
                    });
                    expenses.Add(new CampExpense
                    {
                        CampId = camp1.Id,
                        Category = "Venue, Tents & Facilities",
                        Amount = 4500.00m,
                        Description = "Temporary waterproof shamiana tent canopy and consultation desks rental.",
                        ExpenseDate = DateTime.UtcNow.AddDays(-1),
                        LoggedByUserId = hostUser?.Id
                    });
                }

                if (camp2 != null)
                {
                    expenses.Add(new CampExpense
                    {
                        CampId = camp2.Id,
                        Category = "Medicines & Medical Supplies",
                        Amount = 42000.00m,
                        Description = "Maternal vitamins, pediatric syrups, anti-ulcerants, and sterile delivery kits.",
                        ExpenseDate = DateTime.UtcNow.AddDays(-3),
                        LoggedByUserId = hostUser?.Id
                    });
                    expenses.Add(new CampExpense
                    {
                        CampId = camp2.Id,
                        Category = "Doctor & Staff Honorarium",
                        Amount = 24000.00m,
                        Description = "Honorarium for visiting Gynecologist and Pediatrician specialists.",
                        ExpenseDate = DateTime.UtcNow.AddDays(-2),
                        LoggedByUserId = hostUser?.Id
                    });
                    expenses.Add(new CampExpense
                    {
                        CampId = camp2.Id,
                        Category = "Logistics & Transportation",
                        Amount = 11000.00m,
                        Description = "Speedboat fuel and ambulance standby in Tahirpur haor basin.",
                        ExpenseDate = DateTime.UtcNow.AddDays(-2),
                        LoggedByUserId = hostUser?.Id
                    });
                    expenses.Add(new CampExpense
                    {
                        CampId = camp2.Id,
                        Category = "Refreshments & Volunteers",
                        Amount = 6000.00m,
                        Description = "Meals and drinking water for 12 community volunteers and medical staff.",
                        ExpenseDate = DateTime.UtcNow.AddDays(-1),
                        LoggedByUserId = hostUser?.Id
                    });
                    expenses.Add(new CampExpense
                    {
                        CampId = camp2.Id,
                        Category = "Diagnostic Tools & Equipment",
                        Amount = 5000.00m,
                        Description = "Rapid blood glucose test strips, digital BP cuffs, and pulse oximeters.",
                        ExpenseDate = DateTime.UtcNow.AddDays(-1),
                        LoggedByUserId = hostUser?.Id
                    });
                }

                dbContext.CampExpenses.AddRange(expenses);
                dbContext.SaveChanges();
            }

            // 10. Seed Triage, Consultations, Prescriptions & FollowUps
            if (!dbContext.Consultations.Any())
            {
                var camp = dbContext.Camps.FirstOrDefault(c => c.Status == "Ongoing") ?? dbContext.Camps.FirstOrDefault();
                var doc1 = dbContext.Users.FirstOrDefault(u => u.Role == SystemRoles.Doctor);
                var doc2 = dbContext.Users.Where(u => u.Role == SystemRoles.Doctor).Skip(1).FirstOrDefault() ?? doc1;
                var vol = dbContext.Users.FirstOrDefault(u => u.Role == SystemRoles.Volunteer);
                var pharma = dbContext.Users.FirstOrDefault(u => u.Role == SystemRoles.Pharmacist);
                var patients = dbContext.Users.Where(u => u.Role == SystemRoles.Patient).ToList();
                var medicines = dbContext.MasterMedicines.ToList();

                if (camp != null && doc1 != null && vol != null && patients.Any())
                {
                    var diagnosesList = new[]
                    {
                        ("Hypertension & Cardiovascular Strain", "Blood pressure elevated at 155/95. Recommended low salt diet, lifestyle modifications, and daily monitoring.", "Low sodium diet, gentle walking, avoid smoking.", "Normal"),
                        ("Type 2 Diabetes Mellitus with Neuropathy", "Random blood glucose 14.2 mmol/L. Complaining of peripheral tingling sensation in feet.", "Strict glycemic control, routine foot care.", "Urgent"),
                        ("Upper Respiratory Tract Infection (Seasonal URTI)", "Dry cough, mild fever 101F, pharyngeal congestion. Likely viral with secondary irritation.", "Warm saline gargles, steam inhalation, rest.", "Normal"),
                        ("Acute Gastroenteritis & Dehydration", "Watery diarrhea for 24 hours, weakness. Vitals stable after ORS rehydration.", "Continue oral rehydration saline, zinc supplement.", "Urgent"),
                        ("Osteoarthritis of Bilateral Knees", "Chronic joint stiffness and pain on standing. Recommended low-impact exercises.", "Avoid sitting cross-legged, warm compression.", "Normal"),
                        ("Allergic Contact Dermatitis", "Pruritic rash on both forearms. Exposure to untreated char river water.", "Keep skin dry, use calamine lotion.", "Normal"),
                        ("Nutritional Iron Deficiency Anemia", "Pallor, fatigue, low Hb. Common in rural post-partum women.", "Iron and folic acid rich diet, leafy greens.", "Normal")
                    };

                    int tokenCounter = 101;
                    for (int i = 0; i < patients.Count; i++)
                    {
                        var pat = patients[i];
                        var diagInfo = diagnosesList[i % diagnosesList.Length];
                        var assignedDoc = (i % 2 == 0 ? doc1 : doc2) ?? doc1;
                        if (assignedDoc == null) continue;

                        var triage = new TriageRecord
                        {
                            CampId = camp.Id,
                            PatientId = pat.Id,
                            VolunteerId = vol.Id,
                            RecordedAt = DateTime.UtcNow.AddHours(- (i * 3 + 2)),
                            BloodPressure = i % 2 == 0 ? "140/90" : "120/80",
                            TemperatureF = 98.6 + (i % 3) * 1.1,
                            WeightKg = 52.0 + (i * 6),
                            HeightCm = 158.0 + (i * 3),
                            BMI = 22.4,
                            PresentingSymptoms = diagInfo.Item1,
                            UrgencyLevel = diagInfo.Item4,
                            TokenNumber = tokenCounter++,
                            IsSeenByDoctor = true
                        };
                        dbContext.TriageRecords.Add(triage);
                        dbContext.SaveChanges();

                        var consult = new Consultation
                        {
                            TriageRecordId = triage.Id,
                            DoctorId = assignedDoc.Id,
                            ConsultedAt = triage.RecordedAt.AddMinutes(15),
                            Diagnosis = diagInfo.Item1,
                            ClinicalNotes = diagInfo.Item2,
                            Advice = diagInfo.Item3
                        };
                        dbContext.Consultations.Add(consult);
                        dbContext.SaveChanges();

                        // Prescription
                        var prescription = new Prescription
                        {
                            ConsultationId = consult.Id,
                            IsDispensed = true,
                            DispensedByPharmacistId = pharma?.Id,
                            DispensedAt = consult.ConsultedAt.AddMinutes(10)
                        };
                        dbContext.Prescriptions.Add(prescription);
                        dbContext.SaveChanges();

                        // Add prescription items
                        if (medicines.Any())
                        {
                            var med = medicines[i % medicines.Count];
                            dbContext.PrescriptionItems.Add(new PrescriptionItem
                            {
                                PrescriptionId = prescription.Id,
                                MasterMedicineId = med.Id,
                                Dosage = "1+0+1",
                                DurationDays = 7,
                                Instructions = "After meal with water",
                                QuantityPrescribed = 14,
                                QuantityDispensed = 14
                            });
                            dbContext.SaveChanges();
                        }

                        // Referral for urgent cases
                        if (diagInfo.Item4 == "Urgent")
                        {
                            dbContext.Referrals.Add(new Referral
                            {
                                ConsultationId = consult.Id,
                                ReferredHospital = "Kurigram / Sunamganj District Sadar Hospital",
                                Reason = $"Patient requires comprehensive diagnostic follow-up for {diagInfo.Item1}.",
                                Urgency = "Urgent"
                            });
                            dbContext.SaveChanges();
                        }

                        // Follow up
                        if (i % 2 == 0)
                        {
                            dbContext.PatientFollowUps.Add(new PatientFollowUp
                            {
                                CampId = camp.Id,
                                PatientId = pat.Id,
                                ConsultationId = consult.Id,
                                Reason = $"Post-camp vital signs verification and adherence check for {diagInfo.Item1}.",
                                ScheduledDate = DateTime.UtcNow.AddDays(i + 1),
                                Status = i == 0 ? "Resolved" : "Pending",
                                VolunteerNotes = i == 0 ? "Patient contacted via phone; reports symptoms subsided." : null,
                                CreatedAt = DateTime.UtcNow.AddHours(-10),
                                LastContactedAt = i == 0 ? DateTime.UtcNow.AddHours(-1) : null
                            });
                            dbContext.SaveChanges();
                        }
                    }
                }
            }
        }
    }
}

